enum CONSUME {
    MAIN = 'MAIN',
    MAIN_CONTINUE = 'MAIN_CONTINUE',
    STATEMENT = 'STATEMENT',

    EXPRESSION = 'EXPRESSION',
    EXPRESSION_OPERATOR = 'EXPRESSION_OPERATOR',
    EXPRESSION_LIST = 'EXPRESSION_LIST',
    EXPRESSION_LIST_CONTINUE = 'EXPRESSION_LIST_CONTINUE',
    STRING = 'STRING',
    IDENTIFIER = 'IDENTIFIER',
    IDENTIFIER_LIST = 'IDENTIFIER_LIST',
    IDENTIFIER_LIST_CONTINUE = 'IDENTIFIER_LIST_CONTINUE',
    IDENTIFIER_OR_START_BRACKET = 'IDENTIFIER_OR_START_BRACKET',
    START_PARENTHESIS = 'START_PARENTHESIS',
    START_CURLY_BRACKET = 'START_CURLY_BRACKET',
    END_PARENTHESIS = 'END_PARENTHESIS',
    END_CURLY_BRACKET = 'END_CURLY_BRACKET',
    START_BRACKET = 'START_BRACKET',
    END_BRACKET = 'END_BRACKET',
    PARAMETER_LIST = 'PARAMETER_LIST',
    PARAMETER_LIST_CONTINUE = 'PARAMETER_LIST_CONTINUE',
    PARAMETER = 'PARAMETER',
    TERNARY_ELSE = 'TERNARY_ELSE',
}

export { CONSUME };
